export const SELECT_INSTALLATION = "SELECT_INSTALLATION";
export const AVAILABLE_INSTALLATIONS_LOADING =
    "AVAILABLE_INSTALLATIONS_LOADING";
export const AVAILABLE_INSTALLATIONS_LOADED = "AVAILABLE_INSTALLATIONS_LOADED";
export const LOADING = "LOADING";
export const LOADING_DONE = "LOADING_DONE";
